{{- if and .Values.pdb.enabled (ge (int .Values.replicaCount) 2) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "inari-console.fullname" . }}
  labels:
    {{- include "inari-console.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "inari-console.selectorLabels" . | nindent 6 }}
{{- end }}
